`ifndef KECCAK_DEFS_VH
`define KECCAK_DEFS_VH

`define KECCAK_STATE_WIDTH 1600
`define KECCAK_LANE_WIDTH  64
`define KECCAK_NUM_LANES   25
`define KECCAK_NUM_ROUNDS  24
`define SHAKE256_RATE_BITS 1088
`define SHAKE256_RATE_BYTES 136
`define SHAKE256_CAP_BITS   512
`define KECCAK_PIPE_STAGES   4
`define KECCAK_ROUNDS_STAGE  6

`endif